trigger:
  - dev
  - master

pool:
  vmImage: ubuntu-16.04

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
      npm run test
    displayName: "npm install and build"
